# Generated by Django 4.2.16 on 2024-11-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50, null=True)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puesto', models.CharField(max_length=100)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=5)),
                ('septimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insaforp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mensual', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('aguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anios', models.IntegerField(default=1)),
                ('factor_recargo', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('factor_recargo_con_eficiencia', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('moi', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('moh', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cif', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_cif', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tasa_cif', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_loc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_por_linea', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lineas_mes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tiempo_estimado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('aReinvertir', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('activo', models.CharField(max_length=50)),
                ('montoDebe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pasivo', models.CharField(max_length=50)),
                ('montoHaber', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(default='', max_length=100)),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('optimista', models.IntegerField()),
                ('probable', models.IntegerField()),
                ('pesimista', models.IntegerField()),
                ('lineas_esperadas', models.IntegerField()),
                ('costo_modulo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_desarrollo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ordendedesarrollo')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPeriodica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ajusteDebe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ajusteHaber', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estadoResultado', models.BooleanField()),
                ('estadoCapital', models.BooleanField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empleado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordendedesarrollo')),
            ],
        ),
    ]
