# Generated by Django 5.1.2 on 2024-10-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('activo', models.CharField(max_length=50)),
                ('montoDebe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pasivo', models.CharField(max_length=50)),
                ('montoHaber', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='clasificacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='haber',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
