# Generated by Django 5.1.2 on 2024-11-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
