# Generated by Django 4.2.16 on 2024-10-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transaccion_cuenta_clasificacion_cuenta_debe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puesto', models.CharField(max_length=100)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=5)),
                ('septimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insaforp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
