# Generated by Django 5.1.2 on 2024-10-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_empleado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='activo',
            new_name='debe',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='pasivo',
            new_name='haber',
        ),
    ]
