# Generated by Django 5.1.2 on 2024-10-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_empleado_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPeriodica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ajusteDebe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ajusteHaber', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estadoResultado', models.BooleanField()),
                ('estadoCapital', models.BooleanField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.periodo')),
            ],
        ),
    ]
