# Generated by Django 4.2.16 on 2024-11-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_empleado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='anios',
            field=models.IntegerField(default=1),
        ),
    ]
