# Generated by Django 5.1.2 on 2024-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_periodo_cuentaperiodica'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='aReinvertir',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
