# Generated by Django 4.2.16 on 2024-11-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ordendedesarrollo_empleado_factor_recargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='costo_mensual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
