# Generated by Django 5.1.2 on 2024-10-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_periodo_areinvertir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
