# Generated by Django 5.1.2 on 2024-11-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_periodo_fecha_fin'),
        ('myapp', '0008_empleado_costo_mensual'),
    ]

    operations = [
    ]
